---
apiVersion: v1
kind: Pod
metadata:
  name: blockchaincli
spec:
  restartPolicy: "Never"
  volumes:
  - name: shared
    persistentVolumeClaim:
      claimName: shared-pvc
  - name: composer-card-store
    persistentVolumeClaim:
      claimName: composer-pvc
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
  - name: blockchaincli
    image: ibmblockchain/fabric-tools:1.1.0
    imagePullPolicy: Always
    command: ["sh", "-c", "while true; do echo hello; sleep 1; done;"]
    volumeMounts:
    - mountPath: /shared
      name: shared
    - mountPath: /home/composer/.composer
      name: composer-card-store      
---
