---
apiVersion: v1
kind: Pod
metadata:
  name: composer-cli
spec:
  restartPolicy: "Never"
  volumes:
  - name: composer-card-store
    persistentVolumeClaim:
      claimName: composer-pvc
  - name: shared
    persistentVolumeClaim:
      claimName: shared-pvc
  containers:
  - name: composer-cli
    image: ibmblockchain/composer-cli:0.19.5
    imagePullPolicy: Always
    command: ["sh", "-c", "while true; do echo hello; sleep 1; done;"]
    volumeMounts:
    - name: composer-card-store
      mountPath: /home/composer/.composer
    - name: shared
      mountPath: /shared



