---
apiVersion: v1
kind: Pod
metadata:
  name: wipeshared
spec:
  restartPolicy: "Never"
  volumes:
  - name: shared
    persistentVolumeClaim:
      claimName: shared-pvc

  containers:
  - name: wipeshared
    image: hyperledger/fabric-tools:1.2.1
    imagePullPolicy: Always
    command: ["sh", "-c", "rm -rf /shared/*"]
    volumeMounts:
    - mountPath: /shared
      name: shared
